HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sovereign AI</title><style>
:root{font-family:Segoe UI,system-ui,sans-serif;color:#d8e5ed;background:#101820}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 80% 0,#1e4057,#101820 48%)}
header{padding:20px 28px;border-bottom:1px solid #285264;display:flex;justify-content:space-between}main{max-width:1200px;margin:auto;padding:28px}.card{background:#172631;border:1px solid #285264;border-radius:14px;padding:20px;margin-bottom:18px}h1{color:#f4b942}button{background:#1e4057;border:1px solid #3a7084;color:white;padding:10px 14px;border-radius:8px;cursor:pointer}input,textarea{width:100%;background:#0b1218;color:white;border:1px solid #285264;border-radius:8px;padding:10px;margin:6px 0 12px}.hidden{display:none}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}#messages,#activity,#evidence{white-space:pre-wrap;background:#0b1218;border-radius:8px;padding:14px;min-height:180px;overflow:auto}.ok{color:#74c69d}.bad{color:#f28482}@media(max-width:760px){.grid{grid-template-columns:1fr}main{padding:14px}}
</style></head><body><header><strong>SOVEREIGN AI</strong><span>Local-only workbench</span></header><main>
<section id="auth" class="card"><h1>Local sign in</h1><input id="user" placeholder="Username"><input id="pass" type="password" placeholder="Password"><button onclick="login()">Sign in</button><button onclick="setup()">Create first admin</button><p id="authmsg"></p></section>
<section id="app" class="hidden"><div class="grid"><div class="card"><h1>Chat</h1><select id="model"></select><textarea id="prompt" rows="4" placeholder="Ask Tony Stark..."></textarea><button onclick="sendTask()">Run task</button><button onclick="approve()">Approve result</button><div id="messages"></div><h3>Live activity</h3><div id="activity"></div></div><div class="card"><h1>Knowledge</h1><input id="upload" type="file"><button onclick="upload()">Ingest locally</button><input id="question" placeholder="Search local evidence"><button onclick="ask()">Ask FRIDAY</button><div id="evidence"></div><h3>Documents</h3><div id="docs"></div></div></div><div class="card"><h1>System</h1><div id="health"></div><button onclick="logout()">Logout</button></div></section></main>
<script>
let token='',taskId=null;const api=(path,opts={})=>{opts.headers={...(opts.headers||{}),Authorization:'Bearer '+token,'Content-Type':'application/json'};return fetch(path,opts).then(async r=>{let x=await r.json();if(!r.ok)throw Error(x.error||r.status);return x})};
function msg(x){document.querySelector('#authmsg').textContent=x}async function setup(){try{await fetch('/api/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:user.value,password:pass.value})});msg('Admin created. Sign in now.')}catch(e){msg(e.message)}}async function login(){try{let x=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:user.value,password:pass.value})});let y=await x.json();if(!x.ok)throw Error(y.error);token=y.token;auth.classList.add('hidden');app.classList.remove('hidden');load()}catch(e){msg(e.message)}}async function load(){let h=await fetch('/api/health').then(r=>r.json());health.innerHTML=Object.entries(h).map(([k,v])=>`<p class="${v[0]?'ok':'bad'}">${k}: ${v[1]}</p>`).join('');let m=await api('/api/models');model.innerHTML=m.models.map(x=>`<option>${x}</option>`).join('')||'<option>local-model</option>';let d=await api('/api/knowledge/documents');docs.innerHTML=d.map(x=>`<p>${x.original_name} | ${x.processing_status} | v${x.version}</p>`).join('')||'No documents'}async function sendTask(){let x=await api('/api/tasks',{method:'POST',body:JSON.stringify({request:prompt.value,model:model.value})});taskId=x.task_id;messages.textContent='Task '+taskId+' queued';poll()}async function poll(){let x=await api('/api/tasks/'+taskId);activity.textContent=JSON.stringify(x,null,2);if(!['completed','failed','awaiting_approval'].includes(x.status))setTimeout(poll,500);else messages.textContent=x.output||x.error||x.status}async function approve(){if(taskId)messages.textContent=JSON.stringify(await api('/api/tasks/'+taskId+'/approve',{method:'POST'}))}async function upload(){let f=upload.files[0];if(!f)return;let b=await f.arrayBuffer();let raw=btoa(String.fromCharCode(...new Uint8Array(b)));await api('/api/files',{method:'POST',body:JSON.stringify({name:f.name,content:raw})});load()}async function ask(){let x=await api('/api/knowledge/ask',{method:'POST',body:JSON.stringify({question:question.value,model:model.value})});evidence.textContent=x.answer+'\n\n'+JSON.stringify(x.citations,null,2)}async function logout(){await api('/api/logout',{method:'POST'});location.reload()}
</script></body></html>'''
